"""Markdown issue brief export, matching the reviewable format in prd.md section 28.
Human review status is always shown, and publication_status must be
'approved_publication'-equivalent before anything here should leave the system
(prd.md 9.15 — no public-facing item is published without review)."""

from app.models import Document, Issue, IssueLink


def _score_label(score: int) -> str:
    if score >= 9:
        return "Major"
    if score >= 6:
        return "Significant"
    if score >= 3:
        return "Moderate"
    return "Routine"


def render_issue_brief(db, issue: Issue) -> str:
    lines: list[str] = []
    lines.append(f"# {issue.title}")
    lines.append("")
    lines.append(f"Status: {issue.status.replace('_', ' ').title()}")
    lines.append(f"Jurisdiction: {issue.jurisdiction or 'Unknown'}")
    if issue.agencies_involved:
        lines.append(f"Agencies: {', '.join(issue.agencies_involved)}")
    lines.append(f"Importance: {_score_label(issue.importance_score)}")
    lines.append(f"Urgency: {_score_label(issue.urgency_score)}")
    lines.append(f"Transparency Risk: {_score_label(issue.transparency_risk_score)}")
    lines.append(f"Human Review Status: {issue.review_status.replace('_', ' ').title()}")
    lines.append("")

    lines.append("## What Happened")
    lines.append("")
    lines.append(issue.summary or "_No summary recorded yet._")
    lines.append("")

    events = sorted(issue.events, key=lambda e: e.event_date or e.detected_at, reverse=True)
    if events:
        lines.append("## What Changed Recently")
        lines.append("")
        for event in events[:5]:
            when = event.event_date.date().isoformat() if event.event_date else "date unknown"
            lines.append(f"- {when}: {event.title}")
        lines.append("")

    lines.append("## Next Decision Point")
    lines.append("")
    if issue.next_deadline:
        lines.append(f"Next deadline: {issue.next_deadline.date().isoformat()}")
    else:
        lines.append("No upcoming deadline recorded.")
    lines.append("")

    links = (
        db.query(IssueLink)
        .filter(IssueLink.issue_id == issue.id, IssueLink.document_id.isnot(None))
        .all()
    )
    if links:
        lines.append("## Key Documents")
        lines.append("")
        for link in links:
            doc = db.get(Document, link.document_id)
            if not doc:
                continue
            label = doc.title or doc.document_type or "Document"
            url = doc.original_url or doc.archive_path
            lines.append(f"- [{label}]({url})")
        lines.append("")

    lines.append("## Assessment")
    lines.append("")
    lines.append(
        issue.summary
        or "This issue has not yet been assessed by a human reviewer. Treat AI-derived "
        "scores above as provisional until reviewed."
    )
    lines.append("")
    lines.append("---")
    lines.append(
        "_This brief was generated by Ventura Civic Radar. Unverified/social claims, if any, "
        "are marked separately in the source timeline and must not be treated as confirmed._"
    )
    return "\n".join(lines)
