"""Formats a NarrativeSummary for email. Kept separate from generate.py so
the email-specific wrapping (subject line, minimal HTML shell) doesn't mix
with generation logic, and so tests can check formatting without touching
the AI layer.
"""

import html

from app.config import settings
from app.models import NarrativeSummary


def render_summary_email(summary: NarrativeSummary) -> tuple[str, str, str]:
    """Returns (subject, markdown_body, html_body)."""
    subject = summary.title

    footer = (
        f"\n\n---\nGenerated by {settings.project_name} "
        f"({summary.period_type} recap, {summary.period_start.date().isoformat()} to "
        f"{summary.period_end.date().isoformat()}). "
    )
    if summary.error_message:
        footer += f"Note: narrative generation had an issue ({summary.error_message}); showing the raw rollup instead."
    markdown_body = summary.narrative_markdown + footer

    # Minimal HTML shell rather than a real markdown renderer -- a <pre>
    # block keeps headers/bullets/emphasis legible without adding a new
    # dependency; most mail clients render monospace fine for a short recap.
    html_body = (
        "<html><body>"
        f"<pre style=\"font-family: -apple-system, sans-serif; white-space: pre-wrap;\">"
        f"{html.escape(markdown_body)}</pre>"
        "</body></html>"
    )
    return subject, markdown_body, html_body
